addSbtPlugin("org.scalameta" % "sbt-scalafmt"      % "2.5.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc"          % "2.9.0")
addSbtPlugin("com.github.sbt" % "sbt-github-actions" % "0.29.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"     % "1.11.2")
addSbtPlugin("com.github.sbt" % "sbt-git"            % "2.1.0")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin"    % "1.1.5")
