package bench

import java.nio.file.{Files, Paths}

/**
 * Generates a deeply-chained registry of `n` entries using one of the prepend operators (`+:`, `*:`, `-:`)
 * and writes the test source to `bench/src/bench/scala/bench/BigRegistry<Variant>Spec.scala`.
 *
 * The output lives under the custom `Bench` sbt configuration so it is *not* compiled by the regular
 * `sbt test` run. To exercise it: `sbt bench/Bench/test`.
 *
 * Schema: T0 and T1 are leaf values; every later T_i is a case class consuming T_{i-2} and T_{i-1}.
 * The registry is built bottom-up so the strict `+:` check passes.
 *
 * Run via: `sbt "bench/runMain bench.generate --n=100 --op=+:"`.
 * Without `--op`, all three variants are generated.
 */
@main def generate(args: String*): Unit =
  val n = args.collectFirst { case s if s.startsWith("--n=") => s.drop(4).toInt }.getOrElse(100)
  val op = args.collectFirst { case s if s.startsWith("--op=") => s.drop(5) }

  op match
    case Some(o) => writeOne(n, o, classNameFor(o))
    case None =>
      writeOne(n, "+:", "BigRegistryStrictSpec")
      writeOne(n, "*:", "BigRegistryTrackedSpec")
      writeOne(n, "-:", "BigRegistryUntypedSpec")

private def classNameFor(op: String): String = op match
  case "+:"  => "BigRegistryStrictSpec"
  case "*:"  => "BigRegistryTrackedSpec"
  case "-:"  => "BigRegistryUntypedSpec"
  case other => sys.error(s"Unknown op: $other (expected +:, *:, or -:)")

private def writeOne(n: Int, op: String, className: String): Unit =
  val variantLabel = className.stripPrefix("BigRegistry").stripSuffix("Spec")
  val cacheTags = sys.env.get("CACHE_TAGS").contains("1")

  val sb = StringBuilder()
  sb ++= s"// Auto-generated by bench.Generate. Variant: $variantLabel ($op). cacheTags=$cacheTags\n"
  sb ++= "package bench\n\n"
  sb ++= "import org.specs2.mutable.Specification\n"
  sb ++= "import registry.*\n"
  if cacheTags then sb ++= "import izumi.reflect.Tag\n"
  sb ++= "\n"
  sb ++= s"class $className extends Specification:\n\n"
  sb ++= s"  import $className.*\n\n"
  sb ++= s"  \"$variantLabel: build a $n-entry registry and resolve the top of the chain at runtime\" >> {\n"
  sb ++= s"    bigRegistry.make[T${n - 1}] must not(beNull)\n"
  sb ++= "  }\n\n"

  sb ++= s"object $className:\n"
  for i <- 0 until 2 do sb ++= s"  case class T$i(x: Int)\n"
  for i <- 2 until n do sb ++= s"  case class T$i(a: T${i - 2}, b: T${i - 1})\n"

  if cacheTags then
    sb ++= "\n  // Pre-cached Tag givens — each unique type pays izumi-reflect's macro cost only once.\n"
    for i <- 0 until n do sb ++= s"  given tagT$i: Tag[T$i] = summon[Tag[T$i]]\n"

  sb ++= "\n  val bigRegistry =\n"
  for i <- (n - 1) until 1 by -1 do sb ++= s"    fun[T$i] $op\n"
  sb ++= s"    value(T1(1)) $op\n"
  sb ++= s"    value(T0(0)) $op\n"
  sb ++= "    Registry.empty\n"

  val out = Paths.get(s"bench/src/bench/scala/bench/$className.scala")
  Files.createDirectories(out.getParent)
  Files.writeString(out, sb.toString)
  println(s"Wrote $out (${sb.length} chars, $n entries, op=$op, cacheTags=$cacheTags)")
